// Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
package main

import "fmt"

func fib(r int) int {
	a, b := 1, 1
	for i := 3; i < r; i++ {
		c := a + b
		a = b
		b = c
	}
	return b
}

func main() {
	var sum int
	var lastFibValue int
	lastFib := 3

	for lastFibValue < 4000000 {
		lastFibValue = fib(lastFib)

		if lastFibValue%2 == 0 {
			sum += lastFibValue
		}

		lastFib++
	}

	fmt.Printf("sum of the even-valued terms: %v", sum)
}
